language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"

install:
  - pip install --editable .
  - pip install blinker

script: make test

notifications:
  email: false
  irc:
    channels:
      - "irc.airwired.org#alumni"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
